M48
; DRILL file {KiCad 9.0.5-1.fc42} date 2025-11-14T19:16:13+1030
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-14T19:16:13+10:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-1.fc42
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X140.075Y-50.03
X144.925Y-50.03
T2
X139.775Y-47.0
X145.225Y-47.0
M30
