M48
; DRILL file {KiCad 9.0.5-1.fc42} date 2025-11-08T23:03:27+1030
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-08T23:03:27+10:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-1.fc42
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X130.075Y-80.03
X134.925Y-80.03
T2
X129.775Y-77.0
X135.225Y-77.0
M30
