M48
; DRILL file {KiCad 9.0.5-1.fc42} date 2025-11-14T21:23:54+1030
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-14T21:23:54+10:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-1.fc42
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X318.53Y-297.075
X318.53Y-301.925
T2
X315.5Y-296.775
X315.5Y-302.225
M30
